development:
  adapter: postgresql
  encoding: unicode
  database: sample_app_dev
  pool: 5
  username: superdev
  password: superdev

test:
  adapter: postgresql
  encoding: unicode
  database: sample_app_test
  pool: 5
  username: superdev
  password: superdev
